{% set name = "nestedtext" %}
{% set version = "3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nestedtext-{{ version }}.tar.gz
  sha256: 8837596bdb5936b05ead4517713dc67f8118760ef59e58777475d4a8dd20cbac

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - flit-core >=2,<4
    - pip
  run:
    - python >=3.6
    - inform >=1.28

test:
  imports:
    - nestedtext
  commands:
    - pip check
  requires:
    - pip

about:
  summary: human readable and writable data interchange format
  description: |
    NestedText is a file format for holding structured data. It is similar in
    concept to JSON, except that NestedText is designed to make it easy for
    people to enter, edit, or view the data directly. It organizes the data into
    a nested collection of name-value pairs, lists, and strings. The syntax is
    intended to be very simple and intuitive for most people.
  license: MIT
  license_file: LICENSE
  home: https://nestedtext.org
  doc_url: https://nestedtext.org
  dev_url: https://github.com/KenKundert/nestedtext


extra:
  recipe-maintainers:
    - KenKundert
